### ISSUE TITLE
dev_christian: leere Tabelle anders darstellen

### ISSUE THREAD

**Issue by eberhardt** [innocampus/moodle-local_assessment_methods#4]
Bei einem leeren Datensatz die Tabelle nicht rendern, sondern eine Nachricht ausgeben, die besagt, dass es keine Daten gibt.

**Comment by travellingbully** [comment]
Bei meinem Vorschlag wird vorab geprüft, ob die Daten leer sind, und es wird nur gerendert, wenn sie das nicht sind. Ob es jetzt noch Randfälle gibt, um die es sich Gedanken zu machen gilt, sei dahingestellt. :)

**Comment by eberhardt** [comment]
Das geht etwas schicker, guck mal hier:
https://github.com/innocampus/moodle-local_assessment_methods/blob/2bc53c979855830ef0584bc86b73bcd5dbf43870/classes/manager.php#L136-L141

**Comment by travellingbully** [comment]
Habe ich so übernommen. Die Firma dankt! :)

**Comment by eberhardt** [comment]
Übernimmt jetzt die Klasse report_table, sehe ich das richtig? ^^

**Comment by travellingbully** [comment]
Genau! table_sql ist ziemlich mächtig und hat viele Funktionen, die mir das Paging und Sortieren u.a. erleichterten. :)

**Comment by eberhardt** [comment]
Na dann. ^^
