### ISSUE TITLE
dev_christian: Datensatz der Tabelle filtern

### ISSUE THREAD

**Issue by eberhardt** [innocampus/moodle-local_assessment_methods#5]

**Comment by eberhardt** [comment]
Gibt es hier schon etwas Neues, @travellingbully ?
Ich denke html_writer::table wird dabei nicht zur Lösung führen. Vielleicht müssen wir da schon jetzt auf die table Klasse gucken:
https://docs.moodle.org/dev/lib/tablelib.php

**Comment by travellingbully** [comment]
Ich versuche es gerade über das Filtern des Datensatzes ($data), welches ich aus der DB gezogen habe, je nachdem welche und wie viele Einschränkungen ich in meine Suchschablone eingebe. Eigentlich dachte ich es wäre sinnvoller, die DB nicht erneut abzufragen, da sie mir ja schon einmal alles geliefert hat. ^^

**Comment by eberhardt** [comment]
Das ist es auch, meinst du, du bekommst das dann schneller fertig? Immerhin müsstest du ja dann evtl. mit Java-Script die Tabelle manipulieren. Zudem müssen wir für den Fall vorsorgen, falls wir irgendwann dann so 1000 Einträge haben... wollen wir dann alle auf eine Seite anzeigen? Da brauchen wir wohl eher nen Paging. /think

**Comment by travellingbully** [comment]
Das ist mir gelungen (table_sql), exemplarisch läuft es jetzt mit 10 Einträgen pro Seite, da ich nur 13 Testeinträge habe. Auch kann man nach Spalte sortieren, standardmäßig wird jetzt nach Datum (neuestes oben) sortiert. Suchen und Export (Download) zicken jetzt noch herum.
![Screenshot from 2022-06-01 15-19-46](https://user-images.githubusercontent.com/86602313/171414348-0919ea12-9d8f-4b4d-8973-b2c91030850c.png)

**Comment by eberhardt** [comment]
Ich habe ein Problem mit dem Report in meiner Testinstanz, weil ich leere Zeilen zurück bekomme:
![grafik](https://user-images.githubusercontent.com/3863367/173848832-2ed4ba59-1980-4d2c-b609-01561ec14e1a.png)

Hab es allerdings gelöst gehabt indem ich hier:
https://github.com/innocampus/moodle-local_assessment_methods/blob/0ac8bd1c1c1d7718cbc302bb1080ae0e76b7abad/classes/output/report_table.php#L95-L96
Von FULL JOIN auf LEFT JOIN gewechselt habe. FULL JOIN wird wohl zudem nicht von MySQL unterstützt. Da wir allerdings das Plugin mit anderen Teilen wollen, sollte es kompatibel sein. Ist dort FULL JOIN wirklich notwendig? Reicht nicht auch ein LEFT JOIN?

Also noch 2 Anpassungen:
1. Bug bereinigen
2. Debug-Outputs entfernen.

Für später könnte man sich merken, dass das Filter-Form ein bissle schicker gemacht wird, wie z.B. ein Drop-Down-Menü beim "Aktivitäten"-Filter. Aber das ist erst einmal nebensächlich.

**Comment by travellingbully** [comment]
Guten Morgen Jan,

danke für die Rückmeldung und das Feedback! Tatsächlich hatte ich mit dem LEFT JOIN ursprünglich Probleme, dass damit Einträge übergangen wurden, nachdem ich das UNION ersetzt habe durch die CASE ... WHEN. Mit dem FULL JOIN schien das dann zu funktionieren. Dem ging also eine Überlegung hervor, würde mich aber selbstverständlich sehr freuen, wenn ein LEFT JOIN reichte.

Drop-Down-Menüs habe ich schon eingefügt, waren nur beim letzten Commit noch nicht dabei. Problem, was ich jetzt noch habe, ist, dass aufgrund der Tatsache, dass sich das Datum aus zwei Tabellen speist, diese Filterung noch nicht richtig funktioniert, und der Export der Tabellen ist auch noch buggy. Ich pushe mal den aktuellen Stand, dann siehst du, was ich meine.

Liebe Grüße! :)

**Comment by eberhardt** [comment]
Alright, funktioniert jetzt.
Hast du das Paging wieder ausgeschalten oder nur hoch geschraubt?

**Comment by travellingbully** [comment]
Habe es auf 30 Einträge hochgeschraubt. Davor waren es für Testzwecke 10. Hast du eine spezielle Anzahl ins Auge gefasst? Falls wir irgendwann die angekündigten 1000 Einträge knacken, müssen wir uns überlegen, auf wie viele Seiten wir sie perspektivisch verteilen wollen.

**Comment by eberhardt** [comment]
Alles klar. Das müssen wir dann mit Martin absprechen. Er will diese Funktion am meisten.
Aber dann ist es ja auch erledigt.
